version: "3.3"

services:

#  web:
#    build: .
#    container_name: sofit-web
#    restart: always
#    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
#    volumes:
#      - .:/code
#    ports:
#      - 8000:8000
#    depends_on:
#      - rabbitmq
#    networks:
#      - main

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    restart: always
    networks:
      - main

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    restart: always
    networks:
      - main





#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: sofit-rabbitmq
#    hostname: rabbitMQ
#    restart: always
#    ports:
#      - 5672:5672
#      - 15672:15672
#    volumes:
#      - rabbitmq:/var/lib/rabbitmq
#      - ./core/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#    networks:
#      - main

networks:
  main:
#volumes:
#  rabbitmq:
